
[project]
name = "jdev2026-python-wheel-agranier"
version = "0.1.1"
description = "Demo package"
authors = [{name="Alexandre"}]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools.package-data]
"jdev2026_python_wheel_agranier" = ["data/*.npz"]

[project.scripts]
decrypt-tool = "jdev2026_python_wheel_agranier.decrypt_rsa:run_decrypt_rsa"
